---
title: Geostatistics – Handling Spatial and Spatial-temporal data Using R (GSFE01)
author: Guillaume Blanchet & Steve Vissault
date: November 18-22th, 2019
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

# **Day 1** 

## Introduction

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/index.html)

## Handling spatial data with R

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/basics)

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/basics/practice.html)

# **Day 2**

## Morning - Inverse Distance weigthing

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/IDW/index.html)

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/IDW/practice.html)

## Afternoon - Trend surface estimation

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/trend_surface/index.html)

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/trend_surface/practice.html)

# **Day 3**. Spatial variogram modelling

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/sp_vario/index.html)

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/sp_vario/practice.html)

# **Day 4**. Spatio-temporal data and modelling

## Visualizing spatio-temporal data with R

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/st_manip/index.html)

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/st_manip/practice.html)

## Spatio-temporal variogram practice

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/sp_time_vario/practice.html)

## Spatial modelling with INLA

### `r icon::fa("slideshare")` [Slides](https://steveviss.github.io/PR-GSFE01/INLA/index.html)

### `r icon::fa("tag")` Practices: [Building a mesh in INLA](https://steveviss.github.io/PR-GSFE01/INLA/practiceMesh.html) & [Spatial modelling with INLA](https://steveviss.github.io/PR-GSFE01/INLA/practiceINLASpace.html)

# **Day 5**. Spatio-temporal modelling with INLA

### `r icon::fa("tag")` [Practice](https://steveviss.github.io/PR-GSFE01/INLA/practiceINLASpaceTime.html)
