---

# R basics

### Working directory

It is well known that users are often struggling with their active working directory: where R is reading and writing files on your computer.

Some hints / functions to deal with that aspect:

```{r, eval = FALSE}
getwd() # Print the path of the active folder / working directory
setwd(choose.dir()) 
# 1. setwd() is a function to set a new active directory
# 2. choose.dir() works exclusively on windows 
# This function opens a dialog box to set your custom working directory
dir() # function which list all the files in the working directory.
```

---
# `sf` vs `sp`

```{r}
longitude <- c(-116.7, -120.4, -116.7, -113.5, -115.5, -120.8, -119.5, -113.7, -113.7, -110.7)
latitude <- c(45.3, 42.6, 38.9, 42.1, 35.7, 38.9, 36.2, 39, 41.6, 36.9)
lonlat <- cbind(longitude, latitude)
```

---
# `sf` vs `sp`

.pull-left[
### sp
```{r}
library(sp)
pts <- SpatialPoints(lonlat)
pts
```
]

--

.pull-right[
### sf
```{r}
library(sf)
pts <- st_multipoint(lonlat)
pts
```
]
