
---
class: inverse, center, middle

# List

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=720px></html> 


---

# List

A list store collections of objects (single value, vector or matrix).

```{r}
l <- list(
  v = c(1,2,3,4),
  m = matrix(c(1,1,1,1),nrow=2,ncol=2)
)
```
```{r}
l
```

---

# List

```{r}
l <- list(
  v = c(1,2,3,4),
  m = matrix(c(1,1,1,1),nrow=2,ncol=2)
)
```
```{r results="hold"}
l$v
#equivalent: l[['v']]
```

---

# List

```{r}
l <- list(
  v = c(1,2,3,4),
  m = matrix(c(1,1,1,1),nrow=2,ncol=2)
)
```
```{r results="hold"}
l$m 
#equivalent: l[['m']]
```

---

# List

```{r}
l <- list(
  v = c(1,2,3,4),
  m = matrix(c(1,1,1,1),nrow=2,ncol=2)
)
```

```{r}
l$v[2]
```

---
# `sf` vs `sp`

```{r}
longitude <- c(-116.7, -120.4, -116.7, -113.5, -115.5, -120.8, -119.5, -113.7, -113.7, -110.7)
latitude <- c(45.3, 42.6, 38.9, 42.1, 35.7, 38.9, 36.2, 39, 41.6, 36.9)
lonlat <- cbind(longitude, latitude)
```

---
# `sf` vs `sp`

.pull-left[
### sp
```{r}
library(sp)
pts <- SpatialPoints(lonlat)
pts
```
]

--

.pull-right[
### sf
```{r}
library(sf)
pts <- st_multipoint(lonlat)
pts
```
]
